// <auto-generated />
namespace WebCSharp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Drop2Tb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drop2Tb));
        
        string IMigrationMetadata.Id
        {
            get { return "202310091900483_Drop2Tb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
